<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Entry Go live</name>
   <tag></tag>
   <elementGuidId>8755dd3b-1104-409f-a193-606d56c4d59e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvGoLive_ibGoLive_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvGoLive_ibGoLive_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4241a0a-d10b-4521-bb03-ed5c80b90f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>7185c2e8-027e-43ab-87e1-584270184842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvGoLive$ctl02$ibGoLive</value>
      <webElementGuid>8c61d9a1-de6e-4372-ad0c-bed9b21fe7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvGoLive_ibGoLive_0</value>
      <webElementGuid>7674517b-64bb-453b-8aa8-42cb70955990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Images/Edit.gif</value>
      <webElementGuid>052f565e-e9af-4a09-8f04-aa2d9a70d75d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvGoLive_ibGoLive_0&quot;)</value>
      <webElementGuid>75717f0e-716e-437e-a565-f3ffb1f7ed68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Go Live/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage</value>
      <webElementGuid>4fa21872-16a0-41ad-83f2-7c8efc76eac6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvGoLive_ibGoLive_0']</value>
      <webElementGuid>c30f82e3-5794-477a-8d2a-070b77cafc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvGoLive']/tbody/tr[2]/td[8]/input</value>
      <webElementGuid>a2d67e11-10f7-409e-a9ef-4be67d4bc1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/input</value>
      <webElementGuid>362759ea-f99e-49db-a398-3ef2b119d4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'gvGoLive$ctl02$ibGoLive' and @id = 'gvGoLive_ibGoLive_0' and @src = '../../../Images/Edit.gif']</value>
      <webElementGuid>e4f6df49-8c69-47f0-937a-5b19c3f8dffb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
