<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Entry</name>
   <tag></tag>
   <elementGuidId>414220ea-a456-46ff-8938-1770a1fdb687</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvSupplBranchList_ibEd_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvSupplBranchList_ibEd_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97c76946-cc6e-4a16-8c82-223064254686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>e5299cc3-29bb-40c2-a45d-b6c4a59b8826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvSupplBranchList$ctl02$ibEd</value>
      <webElementGuid>4366948b-6189-44f1-96c8-0869bd646ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvSupplBranchList_ibEd_0</value>
      <webElementGuid>fd0d34dc-8f93-483c-8193-27ad90c1668b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Images/Edit.gif</value>
      <webElementGuid>8d5abfac-14de-4926-a308-07b5a22e74a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;gvSupplBranchList$ctl02$ibEd&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>2926fc00-8c9c-43d4-8d1c-67a77580d896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvSupplBranchList_ibEd_0&quot;)</value>
      <webElementGuid>bd47b376-014e-4980-bd63-1adcd35316fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Purchase Order/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>cb3a354d-a4c1-4d68-8e47-e64eb99cb0b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvSupplBranchList_ibEd_0']</value>
      <webElementGuid>385e02c5-0bf7-4fbe-b25c-16e1c2526b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvSupplBranchList']/tbody/tr[2]/td[5]/input</value>
      <webElementGuid>ce3350df-4de2-42f0-ad4c-87ea50e4c8ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>ba6b533e-e060-4107-a14f-061c8e670ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'gvSupplBranchList$ctl02$ibEd' and @id = 'gvSupplBranchList_ibEd_0' and @src = '../../../Images/Edit.gif']</value>
      <webElementGuid>693e80fd-bbd0-4afb-b9ec-46ff7fc3384b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
