<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Application Number</name>
   <tag></tag>
   <elementGuidId>1114e91a-b15a-44ae-8ef8-3a834a324de8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucSearch_txtAppNo_ltlAppAppNoSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucSearch_txtAppNo_ltlAppAppNoSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucSearch_txtAppNo_ltlAppAppNoSearch</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c792b981-85c8-4cea-9349-802130a97cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucSearch$txtAppNo_ltlAppAppNoSearch</value>
      <webElementGuid>94666945-ebf2-4acb-8c83-8a5b4f78a927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e4cac417-2904-4f10-bb9d-0fad2abcf540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>539APP20240300326</value>
      <webElementGuid>5d2c2554-5568-42a8-b1bb-94effcae565b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucSearch_txtAppNo_ltlAppAppNoSearch</value>
      <webElementGuid>55d28313-a0c8-466a-994c-2cda84da3d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtLongInputStyle</value>
      <webElementGuid>dbc7b87a-db4f-44d8-873f-cc527818dea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucSearch_txtAppNo_ltlAppAppNoSearch&quot;)</value>
      <webElementGuid>1aa35052-f148-4b05-b51d-11b78c47d439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Purchase Order/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>6871f815-fa47-4d57-96ac-db53ac13adba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucSearch_txtAppNo_ltlAppAppNoSearch']</value>
      <webElementGuid>4da01731-55cf-422f-8b2f-f3d2615c2000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucSearch_tblFixedSearch']/tbody/tr/td[4]/input</value>
      <webElementGuid>9eab3f5c-8046-4761-911c-c839649a3679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>9279a38e-0012-4ec9-8e5e-33d459db8a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucSearch$txtAppNo_ltlAppAppNoSearch' and @type = 'text' and @id = 'ucSearch_txtAppNo_ltlAppAppNoSearch']</value>
      <webElementGuid>19f7c730-682c-46da-ac51-9bc9e68cf7f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
