<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Action</name>
   <tag></tag>
   <elementGuidId>ef59bea8-5e7f-4a90-a6e8-92d1cebf8a74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvSupp_ibInvoice_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvSupp_ibInvoice_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41a85ee3-eea5-429a-b45e-d87cc655a6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>c36582ad-2ed5-4efa-9951-3b93a2ee2343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvSupp$ctl02$ibInvoice</value>
      <webElementGuid>9b59aa44-da35-4fa2-aa61-5863928a61e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvSupp_ibInvoice_0</value>
      <webElementGuid>f9e98a6e-cfa1-4822-a8c1-8469b1e3c6f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Images/Edit.gif</value>
      <webElementGuid>1acb64b3-def3-4bb5-a871-4f8aa8be9157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvSupp_ibInvoice_0&quot;)</value>
      <webElementGuid>b07bb4ad-b370-4d7a-a23b-caa1eda2d8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Inovice/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>22007a00-f184-481f-8213-caa26ec6b79a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvSupp_ibInvoice_0']</value>
      <webElementGuid>4059349c-dffd-4869-b5e5-a312e5f4f300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvSupp']/tbody/tr[2]/td[5]/input</value>
      <webElementGuid>de512fe9-f2fc-4ee6-ac79-760bedb21676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>8f0a04a5-73c9-4d73-8e18-3fab832fc64b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'gvSupp$ctl02$ibInvoice' and @id = 'gvSupp_ibInvoice_0' and @src = '../../../Images/Edit.gif']</value>
      <webElementGuid>74e410e3-9680-4396-8f55-e1d94b669560</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
