<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>App_num</name>
   <tag></tag>
   <elementGuidId>b11615f8-89de-4718-8e73-61635401c591</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtInvoiceNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtInvoiceNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtInvoiceNo</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09c1dca7-3ab0-40d0-ab8c-cf99e40040e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtInvoiceNo</value>
      <webElementGuid>3acd573a-1528-4da3-a0fa-0877727eaa37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2647e0c1-ceea-4df3-b467-ef8482ae91ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>b9f6f1d3-d6cd-4af8-a92b-be0dc9c661c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtInvoiceNo</value>
      <webElementGuid>c1def46f-de73-4195-8a57-5eb55570b2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtLongInputStyle</value>
      <webElementGuid>01a5e381-0eee-4676-b22d-852b510882c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtInvoiceNo&quot;)</value>
      <webElementGuid>d789b8c9-c342-4a22-8006-c2037e2750a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Inovice/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>9a0a374e-3ba2-47e7-bd8f-5db40f12fef2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtInvoiceNo']</value>
      <webElementGuid>e21548a1-da87-4143-aba3-37d4241372ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dInvoiceDataSection']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>3ec99cfd-cfea-4316-86c8-68dcadc5d71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1092498e-094c-40ed-80ae-eff19b888f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtInvoiceNo' and @type = 'text' and @id = 'txtInvoiceNo']</value>
      <webElementGuid>a6efe5e9-62ac-4f0b-8779-78dcbba1c696</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
