<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSearch</name>
   <tag></tag>
   <elementGuidId>0365deb8-af2c-4dd1-b5c8-690dbd7be4ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucSearch_btnSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucSearch_btnSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;SEARCH&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b000b6b-abc3-4d71-a6e6-d0890659705d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ceae3e0a-0103-4894-a705-316b91c8941b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucSearch$btnSearch</value>
      <webElementGuid>b2f3f3e2-894f-4484-b819-03a3f3e006bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>58608356-f21f-42a9-b4e2-80738a978775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucSearch_btnSearch</value>
      <webElementGuid>5e13acfb-83d8-43ea-9c6d-12fc821b4b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>8c3b2cb6-99c5-4644-a804-6c8f327f1b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucSearch_btnSearch&quot;)</value>
      <webElementGuid>3cf6b200-3d2c-406a-a997-75f2ac9c140d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Inovice/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>9e173baf-2839-4e27-9bfa-4622b7bcc3e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucSearch_btnSearch']</value>
      <webElementGuid>64722eff-cddf-4f64-a0aa-54deb269b799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucSearch_upButton']/input</value>
      <webElementGuid>65454a8b-751c-4c0c-a9cc-116ae63e1da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>0e5d0c5d-b645-40a4-80a4-8bd83d57247e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ucSearch$btnSearch' and @id = 'ucSearch_btnSearch']</value>
      <webElementGuid>0a399c97-3cf9-41b6-8194-f6a7b851ba8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
