<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cek List Invoice</name>
   <tag></tag>
   <elementGuidId>cbf4c584-86df-49d4-81ca-369e9dd87b9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAvailableInvoiceD_cbSelect_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvAvailableInvoiceD_cbSelect_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvAvailableInvoiceD_cbSelect_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80ff3086-fcc7-4ea4-a690-23984d3acf90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAvailableInvoiceD_cbSelect_0</value>
      <webElementGuid>500c1412-4d60-4827-bf2f-512d3877a850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b40ed2b4-8740-4a49-abf3-e0ccb7dca73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvAvailableInvoiceD$ctl02$cbSelect</value>
      <webElementGuid>485c7d6a-b85b-48d7-a0c8-b3b6dde8738b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvAvailableInvoiceD_cbSelect_0&quot;)</value>
      <webElementGuid>956ae0f3-4870-458b-a893-e0cabcf1d618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Inovice/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>307e4089-aa13-4a53-86f4-0c0729bc32b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvAvailableInvoiceD_cbSelect_0']</value>
      <webElementGuid>43271233-daf9-46c2-8892-8dfd52e0da06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAvailableInvoiceD']/tbody/tr[2]/td/input</value>
      <webElementGuid>57297a11-bb88-4da9-a305-220139196137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td/input</value>
      <webElementGuid>c543a285-9ecc-4587-8bb6-8fded9703599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvAvailableInvoiceD_cbSelect_0' and @type = 'checkbox' and @name = 'gvAvailableInvoiceD$ctl02$cbSelect']</value>
      <webElementGuid>1731022b-226c-437e-89f2-97a077ca61b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
