<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Get Application Number</name>
   <tag></tag>
   <elementGuidId>fd2f3115-f108-41fa-a5b8-ffcb9ae2c0e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAgrmntSelected_lblAppNo_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='gvAgrmntSelected_lblAppNo_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;539APP20240300351&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71dbce58-697d-4e18-b991-14b1112a150c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAgrmntSelected_lblAppNo_0</value>
      <webElementGuid>690ccd3e-6ba6-4411-a96d-890204f6f255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('gvAgrmntSelected$ctl02$lblAppNo','')</value>
      <webElementGuid>0ee47f09-66c6-40ae-af68-c8efd561e4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>539APP20240300351</value>
      <webElementGuid>b0251aaa-2433-469f-83cf-b23f27022038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvAgrmntSelected_lblAppNo_0&quot;)</value>
      <webElementGuid>efdb04f0-7fa2-42a5-bcdc-ba3b7376d64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Inovice/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>173cb722-8ebd-43c0-9396-d95a7b4b5057</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='gvAgrmntSelected_lblAppNo_0']</value>
      <webElementGuid>b4210755-5667-41ba-9548-1bc227f7c6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAgrmntSelected']/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>a5e238c5-cde4-466d-b6fc-ce6f32b0c8da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'539APP20240300351')]</value>
      <webElementGuid>bff8468d-5d56-4461-b514-bf5a21699030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INVOICE AMOUNT'])[1]/following::a[2]</value>
      <webElementGuid>915dd6d2-18c2-488e-b0fb-58f66df356dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTAL PURCHASE ORDER AMOUNT'])[1]/following::a[3]</value>
      <webElementGuid>b07dd375-e5c6-41aa-84c2-6e5aa2165f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HO HENDY'])[1]/preceding::a[2]</value>
      <webElementGuid>3d85b481-4156-4ee6-b576-1f9805a19375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[4]/preceding::a[3]</value>
      <webElementGuid>4c80746e-27a3-47ec-a488-9713134b4afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='539APP20240300351']/parent::*</value>
      <webElementGuid>81cb7506-3a8f-4bc2-8dc3-1f1899a33bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('gvAgrmntSelected$ctl02$lblAppNo','')&quot;)]</value>
      <webElementGuid>f2632968-45ce-4911-86ca-e4b850a8a1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/table/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>ce010b5f-85b6-4e0a-85da-85f808dbaba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'gvAgrmntSelected_lblAppNo_0' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;gvAgrmntSelected$ctl02$lblAppNo&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '539APP20240300351' or . = '539APP20240300351')]</value>
      <webElementGuid>d8015944-4b47-421d-ad78-d5fa708dc650</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
