<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Invoice date</name>
   <tag></tag>
   <elementGuidId>b4bd7fa7-897c-4517-a392-e0c2967e9d56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucDPInvoiceDate_txtDatePicker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucDPInvoiceDate_txtDatePicker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucDPInvoiceDate_txtDatePicker</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>775c5b6d-4ec4-48eb-8957-4734c5d7fb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucDPInvoiceDate$txtDatePicker</value>
      <webElementGuid>ba87b960-49ba-4583-b6a9-c794f51272bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41599f7b-15d6-46ff-bf46-10e9bdb62be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucDPInvoiceDate_txtDatePicker</value>
      <webElementGuid>0d187331-503a-4b73-894d-8091d34c43b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datePicker hasDatepicker</value>
      <webElementGuid>0e4577bd-eeef-48f8-9331-9e18850054e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>copy('ucDPInvoiceDate_txtDatePicker','ucDPInvoiceDate_txtHidden', 'ucDPInvoiceDate_rvDate')</value>
      <webElementGuid>7a45dad3-2883-4401-9c6d-2087edff78f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucDPInvoiceDate_txtDatePicker&quot;)</value>
      <webElementGuid>6da734fa-f0a6-4768-9d0f-3cc3d5e9afa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Inovice/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>563c8b34-af05-4670-967f-6d46801d0fc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucDPInvoiceDate_txtDatePicker']</value>
      <webElementGuid>b9e51429-8cd2-4020-8ae1-9bc1cafe9fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dInvoiceDataSection']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>5d9ebaa2-c9a3-4b8c-8e29-602ce49d1cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>57c39d3b-9e8b-4c83-b3f9-a714523e959a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucDPInvoiceDate$txtDatePicker' and @type = 'text' and @id = 'ucDPInvoiceDate_txtDatePicker']</value>
      <webElementGuid>66ca5b21-c679-4e09-bf10-58b9491a8533</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
