<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save</name>
   <tag></tag>
   <elementGuidId>0a317bd2-fa89-4210-9ed2-6cebb4670460</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lb_Toolbar_Save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lb_Toolbar_Save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>257f1709-f475-47bf-968a-83ce4a1d608f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lb_Toolbar_Save</value>
      <webElementGuid>b44d0da1-a656-4312-b5a8-ba85e7bde67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbMenu</value>
      <webElementGuid>6be6b586-f414-4335-81d8-e9dab312d915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Toolbar_Save&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>4a89998a-f929-4fe3-b654-76a4dcadaebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>5bb6933f-622d-46c1-97d9-52c8a75511ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lb_Toolbar_Save&quot;)</value>
      <webElementGuid>e8eb39f0-e220-4d37-a352-ed86dfbe7855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Delivery Order/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>ec91b756-dd22-4378-9a75-45baadc318fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lb_Toolbar_Save']</value>
      <webElementGuid>b58af12a-aab0-4701-b26e-0bd3a1994949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='toolMenuContainer']/a</value>
      <webElementGuid>272dc838-5acb-4934-80a2-e60c94279244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save')]</value>
      <webElementGuid>32e63fbb-0b18-4414-9b76-17334dc5102d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DELIVERY ORDER'])[1]/following::a[1]</value>
      <webElementGuid>33090598-2ff0-4a78-b897-4f5acd287d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOS\CrdPrc\DeliveryOrder'])[1]/following::a[1]</value>
      <webElementGuid>9f255610-9e54-41b0-8e5e-a4a56ec84e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::a[1]</value>
      <webElementGuid>e9611f82-2ade-46b1-b029-9e57f35da0bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[1]/preceding::a[2]</value>
      <webElementGuid>a47bd1e7-6849-46dc-9463-6040248f1d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>0a84d0d1-bf17-4acf-8eab-8fafce6efabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Toolbar_Save&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>0a86d759-cdfd-4a69-99c5-a7df7c41c661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>1316c41b-bc8f-49a3-913d-666060eba27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lb_Toolbar_Save' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Toolbar_Save&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>51c08de6-2c4e-4fd3-a22e-c88e4f184c8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
