<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Binis Date Confins_train</name>
   <tag></tag>
   <elementGuidId>242edfed-5d3f-404b-b8bd-b58caa81c34c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ltlBusinessDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ltlBusinessDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Friday, 22 March 2024&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4cca44f8-1886-4939-820e-20464685c482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ltlBusinessDate</value>
      <webElementGuid>37a8bfb1-f857-4373-9bbc-e87e0431bbdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>businessDate</value>
      <webElementGuid>f55fa3d0-13f6-4dbf-bea8-d9a2f5ec053f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Friday, 22 March 2024</value>
      <webElementGuid>07b199b7-2cbb-4db7-b73e-05bdbde93d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ltlBusinessDate&quot;)</value>
      <webElementGuid>355a00ff-6c5c-47d4-90ba-82ef25e5d247</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ltlBusinessDate']</value>
      <webElementGuid>c9f0b4ee-2dc3-4777-a830-4d9c659ce873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='navMenu']/span</value>
      <webElementGuid>ad1fe519-fba2-4275-b05f-b082906819a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOME'])[1]/following::span[1]</value>
      <webElementGuid>441d9f73-2bfd-4a92-8cda-30629081e814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SETTING'])[1]/following::span[1]</value>
      <webElementGuid>2d129d6d-2c66-4292-838a-1e604a0d454c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome, Anita Gusti, KEDOYA, Credit Admin'])[1]/preceding::span[1]</value>
      <webElementGuid>c55c2c64-a01c-4eb4-ba5b-341f8c98b5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © AdIns 2011. All Right Reserved'])[1]/preceding::span[3]</value>
      <webElementGuid>fb4a47c7-b5f0-4892-8fb4-a034eaac92df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Friday, 22 March 2024']/parent::*</value>
      <webElementGuid>b96a24ed-d1ae-4906-be46-4a5adb1bac00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span</value>
      <webElementGuid>d708d0f0-2aa4-4a4f-b36e-a0f9f6a440d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ltlBusinessDate' and (text() = 'Friday, 22 March 2024' or . = 'Friday, 22 March 2024')]</value>
      <webElementGuid>e9e04d0a-6610-4ba4-9924-bec7692ccc32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
