<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BLOKIR BPKB</name>
   <tag></tag>
   <elementGuidId>ff9da94f-4f40-4c73-8408-78f451df67d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAssetDoc_lblIsValueNeeded_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='gvAssetDoc_lblIsValueNeeded_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvAssetDoc_lblIsValueNeeded_3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>72a6e917-9f61-4921-8717-7bb9c495d567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAssetDoc_lblIsValueNeeded_3</value>
      <webElementGuid>63442e7f-0c1b-44d6-a8c2-9b95f1d98202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>00be2f82-a5c0-4397-bc37-fcb739cf06fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvAssetDoc_lblIsValueNeeded_3&quot;)</value>
      <webElementGuid>65e0518f-4172-4b91-9815-920c5a6c5ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Delivery Order/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>7ab4fe39-2923-4472-a1ae-b566f17ff754</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='gvAssetDoc_lblIsValueNeeded_3']</value>
      <webElementGuid>f30c80d2-a1e0-4027-914b-cd1063eb2432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAssetDoc']/tbody/tr[5]/td[3]/span</value>
      <webElementGuid>6cf64206-575c-45d9-9b42-e459f8c5ec30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BLOKIR BPKB'])[1]/following::span[1]</value>
      <webElementGuid>d7f4949f-fa6b-42df-905d-c8ceedd1b9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[14]/following::span[4]</value>
      <webElementGuid>4d42f836-02ec-4637-bd86-80daf05f7ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[9]/preceding::span[1]</value>
      <webElementGuid>d4d4a7db-836f-4619-98d4-002ae7af1aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[15]/preceding::span[2]</value>
      <webElementGuid>c64d3cda-310b-43b9-a0c0-0ab731d14e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[3]/span</value>
      <webElementGuid>404b126c-2c3c-49eb-bf7d-4d107edecea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'gvAssetDoc_lblIsValueNeeded_3' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>88cfedb4-07d9-4546-8129-07dc40aeb8af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
