<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CEK NO FAKTUR</name>
   <tag></tag>
   <elementGuidId>82679a26-4e68-4fad-86ba-d1dd68f5fcf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAssetDoc_cbChecked_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvAssetDoc_cbChecked_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvAssetDoc_cbChecked_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72292118-59cc-46cf-9e30-e8a9ad3a6f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAssetDoc_cbChecked_1</value>
      <webElementGuid>fb17bb6a-8fec-4f45-bd81-2d7efb7e526f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d5079b28-2116-4dea-942d-13d96653b8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvAssetDoc$ctl03$cbChecked</value>
      <webElementGuid>24f2acbe-f359-4fad-8ad2-2197a9556425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvAssetDoc$ctl03$cbChecked\',\'\')', 0)</value>
      <webElementGuid>7123ca8b-76e4-4759-9794-e67a80e9fb38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvAssetDoc_cbChecked_1&quot;)</value>
      <webElementGuid>0bade896-ba0b-4025-981c-8eadc7b5dad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Delivery Order/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>5efa2890-74e6-4c99-a9de-8983edfa1a39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvAssetDoc_cbChecked_1']</value>
      <webElementGuid>f1348756-5373-4d10-8fc2-86f85f3f9399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAssetDoc']/tbody/tr[3]/td[5]/input</value>
      <webElementGuid>5a1c6677-e4b6-4ff0-b4ac-a749c34ff927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/input</value>
      <webElementGuid>2d272ec3-e9c2-4c6f-be1d-e3c45eb2e446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvAssetDoc_cbChecked_1' and @type = 'checkbox' and @name = 'gvAssetDoc$ctl03$cbChecked']</value>
      <webElementGuid>888c0449-6dc6-4d3b-a770-6b9271cccc30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
