<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CEK STNK</name>
   <tag></tag>
   <elementGuidId>f8b8a4e6-d98c-4c64-8d7d-cba04c19f0ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAssetDoc_cbChecked_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvAssetDoc_cbChecked_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvAssetDoc_cbChecked_2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66f5930b-1f8e-4df0-9a4b-8d2d0aa1f6b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAssetDoc_cbChecked_2</value>
      <webElementGuid>da187569-f00f-4f56-af61-d3cc558148ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>210bdd2e-7125-46e9-817a-6fe620d8d143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvAssetDoc$ctl04$cbChecked</value>
      <webElementGuid>e95fa238-7a78-4299-a0c6-3c91b31dd169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvAssetDoc$ctl04$cbChecked\',\'\')', 0)</value>
      <webElementGuid>a23c948f-358d-4895-b619-6508248d6243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvAssetDoc_cbChecked_2&quot;)</value>
      <webElementGuid>0df054a1-cf50-49c8-8916-301925aa1cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Delivery Order/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>ffd7eb7f-8172-4fe2-8aa0-640ccda1296e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvAssetDoc_cbChecked_2']</value>
      <webElementGuid>1145ee5c-c2e2-45d2-b6e0-abeb48ca0f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAssetDoc']/tbody/tr[4]/td[5]/input</value>
      <webElementGuid>39a8bb90-10b4-4c16-a2a0-63885538fc14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[5]/input</value>
      <webElementGuid>e9040ec5-afc7-491a-a9a2-75a445345107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvAssetDoc_cbChecked_2' and @type = 'checkbox' and @name = 'gvAssetDoc$ctl04$cbChecked']</value>
      <webElementGuid>bdcdabfe-3e64-4d95-9bf1-1843ab944363</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
