<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DocNo BLOKIR BPKB</name>
   <tag></tag>
   <elementGuidId>a1be90c3-662a-411f-bd91-e07cdf9bf3fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAssetDoc_txtDocNo_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvAssetDoc_txtDocNo_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvAssetDoc_txtDocNo_3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>986b0f9c-2c2a-4987-ba75-f9c5523900f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvAssetDoc$ctl05$txtDocNo</value>
      <webElementGuid>0f53a614-09da-4d99-9ff2-2c7735f0b410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ac63bbcb-0552-4942-9d58-30c199f0bdcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAssetDoc_txtDocNo_3</value>
      <webElementGuid>c1a8d021-222c-41af-8056-cfa0744f59d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
      <webElementGuid>341e7409-b4dc-4968-a38d-8fed03c919ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvAssetDoc_txtDocNo_3&quot;)</value>
      <webElementGuid>26bcfe99-975a-49ba-b1d7-434fb06c4958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Delivery Order/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>edd91617-bac9-4d83-b44c-d3be85d4b923</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvAssetDoc_txtDocNo_3']</value>
      <webElementGuid>a698742a-0673-4444-ab9d-d4fe4d3628a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAssetDoc']/tbody/tr[5]/td[6]/input</value>
      <webElementGuid>3e473314-f4b0-43e0-8301-005a45e27762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[6]/input</value>
      <webElementGuid>eed8433d-0e77-49cd-874d-71015a09696d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'gvAssetDoc$ctl05$txtDocNo' and @type = 'text' and @id = 'gvAssetDoc_txtDocNo_3']</value>
      <webElementGuid>521267f5-7421-4f5b-b8c5-20e3bdcf0441</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
