<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DocNo STNK</name>
   <tag></tag>
   <elementGuidId>e5d386b7-45e3-427c-bf8a-b731000babc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAssetDoc_txtDocNo_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvAssetDoc_txtDocNo_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvAssetDoc_txtDocNo_2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebebb34c-f0bb-469e-a325-2d4275062f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvAssetDoc$ctl04$txtDocNo</value>
      <webElementGuid>f5193c76-9d81-4d28-b364-a41c2469e7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af1e674a-2732-4a01-8b31-bbcac497808e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAssetDoc_txtDocNo_2</value>
      <webElementGuid>24bb4708-9e78-43cd-b46a-9769f20c06d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
      <webElementGuid>e07d3a24-c642-4b1d-89ba-6f82520ce803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvAssetDoc_txtDocNo_2&quot;)</value>
      <webElementGuid>c1a7304d-dcc6-4523-96b9-f03162874b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Delivery Order/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>1f21a216-3937-4d52-91bc-c4160cd8948d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvAssetDoc_txtDocNo_2']</value>
      <webElementGuid>d5603178-f278-471b-a09b-0b7fc4846060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAssetDoc']/tbody/tr[4]/td[6]/input</value>
      <webElementGuid>502af23d-7999-4012-a406-77202b721329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[6]/input</value>
      <webElementGuid>42d991b5-ecc8-440b-8aff-d9d74f996d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'gvAssetDoc$ctl04$txtDocNo' and @type = 'text' and @id = 'gvAssetDoc_txtDocNo_2']</value>
      <webElementGuid>594688a3-b428-4bdb-8198-8331f68cd39e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
