<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Entry DO</name>
   <tag></tag>
   <elementGuidId>9f154ff2-7036-459c-9463-f0e902c286a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAgrmnt_ibDelOrd_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvAgrmnt_ibDelOrd_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36347317-40e2-4335-9c2e-605edabd297f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>e5176ea7-0018-466c-9b6f-654df91a979f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvAgrmnt$ctl02$ibDelOrd</value>
      <webElementGuid>bad75832-ae9f-41e2-baac-be07dcac1866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAgrmnt_ibDelOrd_0</value>
      <webElementGuid>c22fb6a0-3e8c-4170-94bb-e29bd3f3b55b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Images/Edit.gif</value>
      <webElementGuid>3731ff24-5639-436a-80bc-88e6fb2fc18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvAgrmnt_ibDelOrd_0&quot;)</value>
      <webElementGuid>0af9e5ec-58ee-49de-84ca-14a4b4cca856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Delivery Order/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>7e21edee-f485-4ada-a83b-aabda40a6c2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvAgrmnt_ibDelOrd_0']</value>
      <webElementGuid>3d7aaebe-3a02-485a-9578-1bc88409efa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAgrmnt']/tbody/tr[2]/td[8]/input</value>
      <webElementGuid>3e346865-574b-41d9-863b-d91fa75fd7e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/input</value>
      <webElementGuid>b25c73a7-b37d-413f-adbf-52abef724c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'gvAgrmnt$ctl02$ibDelOrd' and @id = 'gvAgrmnt_ibDelOrd_0' and @src = '../../../Images/Edit.gif']</value>
      <webElementGuid>912ee880-b133-454a-8a7e-960429a66461</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
