<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Entry DO_2</name>
   <tag></tag>
   <elementGuidId>c8bcdc2d-96bc-4e83-bb1f-8d31a749a92e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAssetList_ibDelOrd_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvAssetList_ibDelOrd_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16fdf5f0-c6b6-499c-ba1d-87bd04e4d628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>cfffc1ee-45fe-4581-b9d2-f6f240848df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvAssetList$ctl02$ibDelOrd</value>
      <webElementGuid>c5096c74-5005-4fea-b467-3bba1247c392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAssetList_ibDelOrd_0</value>
      <webElementGuid>66ca8598-9d92-4351-9bc9-459a7d7f1e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Images/Edit.gif</value>
      <webElementGuid>76e120cd-c7cd-4894-b22e-6917679d50a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvAssetList_ibDelOrd_0&quot;)</value>
      <webElementGuid>e9aeafa9-ca91-4721-9667-8138ebecddee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Delivery Order/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>15ac83d0-0a4d-4be8-8a0c-7648802e2d61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvAssetList_ibDelOrd_0']</value>
      <webElementGuid>4b9a9c45-8571-4a8d-81a7-664c576498f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAssetList']/tbody/tr[2]/td[11]/input</value>
      <webElementGuid>2c4e65ae-122c-4650-9d96-64646615f4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/input</value>
      <webElementGuid>d92c53c7-d61c-44e1-b9f2-0479d8439863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'gvAssetList$ctl02$ibDelOrd' and @id = 'gvAssetList_ibDelOrd_0' and @src = '../../../Images/Edit.gif']</value>
      <webElementGuid>8e8ba75e-e4ee-47ba-bdcb-ff98f0439018</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
