<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Get application number</name>
   <tag></tag>
   <elementGuidId>570ff5f1-0bf5-4baf-80a8-3f8407f3eb59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucCreditProcessMainInfo_lbAppNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucCreditProcessMainInfo_lbAppNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;539APP20240300351&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f5df1288-2dc2-42fc-b18e-621d504a104f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucCreditProcessMainInfo_lbAppNo</value>
      <webElementGuid>a5c522e5-d7ce-4225-a6c5-b1a89f6cc403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ucCreditProcessMainInfo$lbAppNo','')</value>
      <webElementGuid>319f9ddf-b6e6-4c0e-9153-3f8df3161771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>539APP20240300351</value>
      <webElementGuid>3503d4a3-da4a-4bf7-b0a7-9d3924b47d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucCreditProcessMainInfo_lbAppNo&quot;)</value>
      <webElementGuid>682f56be-087d-48d3-8c54-a467c0e7791b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Delivery Order/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>d9f89aae-e9ff-4bbb-a3ac-add3053fc72e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucCreditProcessMainInfo_lbAppNo']</value>
      <webElementGuid>5d684b50-6e8e-4da4-96da-562d6d9f782b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMainInfoUC']/table/tbody/tr/td[2]/a</value>
      <webElementGuid>be36b613-ecf5-4dec-b4db-b79dc391d033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'539APP20240300351')]</value>
      <webElementGuid>7c13cc3a-c7de-4357-9c47-83485ceb3de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Number'])[1]/following::a[1]</value>
      <webElementGuid>393cccdb-6174-4f89-9d61-e1e424a18b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main Info'])[1]/following::a[1]</value>
      <webElementGuid>2d7c0f48-5838-4838-bbf8-dbf5eb13e37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Num Of Asset'])[1]/preceding::a[1]</value>
      <webElementGuid>b99fec03-8741-4f6b-bcf2-ec967e81e473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agreement No'])[1]/preceding::a[1]</value>
      <webElementGuid>dba89d41-0d3b-4fb9-9fde-9376527fafc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='539APP20240300351']/parent::*</value>
      <webElementGuid>c4b8c694-8d54-402a-8586-48f61a19fec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ucCreditProcessMainInfo$lbAppNo','')&quot;)]</value>
      <webElementGuid>6f200ab4-1ffa-48b1-8781-41ec3bfb81ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>ce6ddc1d-507a-4f8b-bff6-bb04dea8462f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucCreditProcessMainInfo_lbAppNo' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ucCreditProcessMainInfo$lbAppNo&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '539APP20240300351' or . = '539APP20240300351')]</value>
      <webElementGuid>3b509b9b-e646-4a2f-9e0d-25b7b98dda04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
