<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>No Mesin</name>
   <tag></tag>
   <elementGuidId>6ede5754-7e08-4728-81a2-5a4aee6f7d96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtSerialNo2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtSerialNo2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;txtSerialNo2&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4513cba8-7c89-4bd2-8d5d-83bf77884d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtSerialNo2</value>
      <webElementGuid>27dec490-bda7-431e-b7da-e7fd782d604c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2d8bc29e-a6d0-4a0c-ad23-b3e58d1c37a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSerialNo2</value>
      <webElementGuid>d2858ab0-fcc9-4bac-988e-401baffc30d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
      <webElementGuid>0de1e9c4-762f-4edc-ab19-38d10c7971ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSerialNo2&quot;)</value>
      <webElementGuid>9a6ba23b-8598-4727-976c-6125b153b95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Delivery Order/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>df5c0e1e-b0fa-4ea3-b7cd-80d3f8c6c099</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSerialNo2']</value>
      <webElementGuid>afe3f91c-8425-41ec-a572-059fd0ef07f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dDeliveryInfo']/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>cc3c7db8-2aae-40a8-b05a-b9139e76c2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>370bdb3a-4364-4bda-b985-92e37401f806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtSerialNo2' and @type = 'text' and @id = 'txtSerialNo2']</value>
      <webElementGuid>3be1f7aa-35ad-4249-be28-0db6dddba207</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
