<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>No Rangka</name>
   <tag></tag>
   <elementGuidId>c406e5a9-d11f-4855-914e-a71be66d8177</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtSerialNo1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtSerialNo1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;txtSerialNo1&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05f491ea-88ed-4246-bf72-3beff296c4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtSerialNo1</value>
      <webElementGuid>ae7d6809-8d05-456f-95ce-efa93de48575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c95760af-5e7f-4c74-a10c-965e1208beb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSerialNo1</value>
      <webElementGuid>9c54204f-5110-4ddb-a975-d404b8145d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
      <webElementGuid>68af2128-9ef2-42ba-ae05-046b6c55c677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSerialNo1&quot;)</value>
      <webElementGuid>b901df89-703b-4875-8407-b10a53cc3c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Delivery Order/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>ddb16a3b-1235-4b8e-b7fe-07e166e17504</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSerialNo1']</value>
      <webElementGuid>40da3e59-c7eb-479c-8747-7f61952855aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dDeliveryInfo']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>7280ea33-c30c-4b46-99d9-6b58cb87cb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>913c9a11-2c99-4a61-afd6-b1ad31319a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtSerialNo1' and @type = 'text' and @id = 'txtSerialNo1']</value>
      <webElementGuid>0ffa874d-dde8-4513-98c2-83a9f69997b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
