<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Registration Letter Date</name>
   <tag></tag>
   <elementGuidId>cd518a7d-4663-425c-8826-ecac877432d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucDPSpMainDocDt_txtDatePicker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucDPSpMainDocDt_txtDatePicker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucDPSpMainDocDt_txtDatePicker</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a655d55b-d485-4be3-8cb8-9308c1cfe1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucDPSpMainDocDt$txtDatePicker</value>
      <webElementGuid>52e73153-bbed-4355-a574-fa944ef8fa05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36fb394c-a695-4ef5-b802-ccbf7fc85669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucDPSpMainDocDt_txtDatePicker</value>
      <webElementGuid>9db8be7a-6b9e-4137-87f6-a87f373cf056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datePicker hasDatepicker</value>
      <webElementGuid>5040f5a2-6871-4942-8659-da2c56756b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>copy('ucDPSpMainDocDt_txtDatePicker','ucDPSpMainDocDt_txtHidden', 'ucDPSpMainDocDt_rvDate')</value>
      <webElementGuid>d3bac029-2a7b-4993-aad6-ea17907e20b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucDPSpMainDocDt_txtDatePicker&quot;)</value>
      <webElementGuid>ab90a048-1bd0-4911-87db-bbe7011d5508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Delivery Order/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>fac1b4c9-22f5-4846-b084-68156f2436e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucDPSpMainDocDt_txtDatePicker']</value>
      <webElementGuid>219121c7-e670-4a2c-b027-69878ba93ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMainDocLetter']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>670c3fe4-5d82-4b5d-a200-b89b1b37f24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>1f4ac0e7-c699-4fcf-a8a1-e4fe99e31315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucDPSpMainDocDt$txtDatePicker' and @type = 'text' and @id = 'ucDPSpMainDocDt_txtDatePicker']</value>
      <webElementGuid>409815dc-5223-4e0f-8690-f1c6c411ccd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
